services:
  apache:
    build: .             # <--- On a remplacé `image: ...` par ça
    container_name: apache_server
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4.3
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Donner Tous Les Droits nécéssaires au User 
      - ./mysql-init:/docker-entrypoint-initdb.d   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
